FROM node:20 AS builder

ARG BACKEND_URL

WORKDIR /app
COPY . /app

RUN sed -i 's|http://localhost:8000|${BACKEND_URL}|' src/config.tsx

RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

RUN echo '\
server {\
    listen 80;\
    server_name localhost;\
    location / {\
        root /usr/share/nginx/html;\
        index index.html;\
        try_files $uri $uri/ /index.html;\
    }\
}' > /etc/nginx/conf.d/default.conf
